import { Inter } from "next/font/google";
import Layout from "@/components/Layout/Layout";
import { SidebarProvider } from "@/context/SidebarContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Finance Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <Layout>{children}</Layout>
        </SidebarProvider>
      </body>
    </html>
  );
}
